version: '2.1'
services:
  nocodb:
    depends_on:
      root_db:
        condition: service_healthy
    environment:
      NC_DB: "pg://root_db:5432?u=postgres&p=password&d=root_db"
    image: "nocodb/nocodb:0.207.2"
    ports:
      - "8880:8080"
    restart: always
    volumes:
      - "nc_data:/usr/app/data"
  
  root_db:
    environment:
      POSTGRES_DB: root_db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      interval: 10s
      retries: 10
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      timeout: 2s
    image: postgres:13.15
    restart: always
    volumes:
      - "db_data:/var/lib/postgresql/data"
  
  backup:
    image: postgres:13.15
    depends_on:
      root_db:
        condition: service_healthy
    volumes:
      - "db_data:/var/lib/postgresql/data"
      - "./backup:/backup"
    entrypoint: [ "sh", "-c", "PGPASSWORD=${POSTGRES_PASSWORD} pg_dump -h root_db -U ${POSTGRES_USER} ${POSTGRES_DB} > /backup/backup.sql" ]
    restart: "no"

volumes:
  db_data: {}
  nc_data: {}
